library(plyr)
library (dplyr)
library(car)
library(carData)
library(ggrepel)
library(ggfortify)
library(coefplot)
library(gghighlight)
library(lvplot)
library(e1071)
library(scales)
library(rmarkdown)
library(highr)
library(tinytex)
library(shiny)
library(htmlwidgets)
library(pryr)
library(knitr)
library(gtools)
library(survival)
library(pwr)
library(pracma)
library(MASS)
library(DescTools)
library(rafalib)
library(sourcetools)
library(htmltools)
library(plotrix)
#we added all packages

